name: "Test Action"
on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - run: npm version
    - run: npm install
    - run: npm test

    - uses: ./
      with:
        servers: '[{"id": "serverId", "username": "username", "password": "password"}]'
        properties: '[{"prop1": "value1"}, {"prop2": "value2"}]'
        sonatypeSnapshots: true

    - run: cat ~/.m2/settings.xml
      shell: bash